### ISSUE TITLE
Recent releases run errors

### ISSUE THREAD

**Issue by eko5624** [NextFire/mpv-macos-git-builds#2]
It may be brew's bug . Please take a look , thanks .

**Comment by NextFire** [comment]
Looks like today release works again! https://github.com/NextFire/mpv-macos-git-builds/releases/tag/mpv-0.34.0-1-g171627b267

**Comment by NextFire** [comment]
After more digging, it appeared to be caused by https://github.com/google/brotli/issues/934. The fix has been pushed.
