### ISSUE TITLE
Use Lua 5.2

### ISSUE THREAD

**Issue by exc4l** [NextFire/mpv-macos-git-builds#5]
Hi,

if you don't mind I would like you to build mpv with Lua 5.2. The reason being that mpv supports 5.2 and some scripts make use of syntax introduced in 5.2. See: https://github.com/darsain/uosc 

I forked your repository to see how one could do it since homebrew doesn't have a 5.2 formulae.

https://github.com/R-ay/Brew-lua52 provides a basic formulae for 5.2.

Adding the following to your workflow produced a mpv.app capable of running uosc.
curl -L https://raw.githubusercontent.com/R-ay/Brew-lua52/master/lua52.rb > lua52.rb
brew install --build-from-source lua52.rb

**Comment by exc4l** [comment]
If you don't mind. Would be nice if you got run the action and release the new version so that I can just install it via brew. Thank you

**Comment by NextFire** [comment]
The action should run and release automatically in two hours since there are new changes upstream.
