### ISSUE TITLE
Compile with libplacebo master

### ISSUE THREAD

**Issue by eboddington** [NextFire/mpv-macos-git-builds#8]
Hey,

Thanks for this project, it's one of the few working mpv-master macOS builds that I can find.

One suggestion for improvement: would it be possible to build with libplacebo master? This is required for features like the gpu-next vo, which doesn't work when using libplacebo stable. I think it's also generally recommended that mpv from git master should be compiled with its dependencies from git master also (which also means ffmpeg, but that's probably more annoying to sort out)

**Comment by NextFire** [comment]
Done in 022eeafeb1f03510144355231dfa557252654402

**Comment by eko5624** [comment]
Mac doesn't support gpu-next for now, so there's no need compiling libplacebo.

**Comment by NextFire** [comment]
> Mac doesn't support gpu-next for now, so there's no need compiling libplacebo.

gpu-next should be available, it only means that it relies on libplacebo instead of the legacy internal library for rendering. However it will still use OpenGL on macOS instead of Vulkan on other platforms.

**Comment by eboddington** [comment]
> > Mac doesn't support gpu-next for now, so there's no need compiling libplacebo.
> 
> gpu-next should be available, it only means that it relies on libplacebo instead of the legacy internal library for rendering. However it will still use OpenGL on macOS instead of Vulkan on other platforms.

Yep. I’ve used gpu-next on macOS after setting things up myself. Thanks for the change though, this will make it much easier
